version: '3.9'

services:
  mysql-ebook-moim:
    build:
      context: ./db/ebook_moim/
    container_name: mysql-ebook-moim
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - mysql-ebook-moim-storage:/var/lib/mysql
      - ./db/ebook_moim/mysql-confs/:/etc/mysql/conf.d/
      - ./db/ebook_moim/logs:/var/log/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
  ebook-moim:
    build:
      context: ./ebookFinder/
    container_name: ebook-moim
    restart: on-failure
    volumes:
      - ./ebookFinder:/ebook_moim/ebookFinder
    ports:
      - "8000:8000"
    init: true
    entrypoint:
      [ "/ebook_moim/ebookFinder/docker-entrypoint.sh" ]
    depends_on:
      mysql-ebook-moim:
        condition: service_healthy
  redis-ebook-moim:
    image: redis:latest
    container_name: redis-ebook-moim
    restart: always
    ports:
      - '6379:6379'
  nginx-ebook-moim:
    image: nginx:latest
    container_name: nginx-ebook-moim
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ebookFinder/staticfiles:/ebook_moim/ebookFinder/staticfiles
      - ./nginx/logs:/var/log/nginx
      - ./nginx/certs:/etc/letsencrypt
    depends_on:
      - ebook-moim
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certbot:/etc/letsencrypt
      - ./nginx/logs:/var/log/letsencrypt
      - ./nginx/html:/var/www/certbot
    entrypoint: /bin/sh -c "trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew --webroot -w /var/www/certbot; done"
volumes:
  mysql-ebook-moim-storage: {}
